### ISSUE TITLE
AddFunctionToPkg - Change order of parameters

### ISSUE THREAD

**Issue by kwathen** [BioPharmSoftGrp/BaSS#12]
In this function the current order of arguments is
strFunctionName, strPkgDir = "", strFunctionDescription = ""

switch to 

strFunctionName, strFunctionDescription = "", strPkgDir = "", 

since this function is typically used in the package development and will be in the package directory normally strPkgDir == ""

**Comment by nchen4** [comment]
Changed the parameter order and modified the related Rmd files for the instruction templates.
