### ISSUE TITLE
AddTab issue with the standalone App

### ISSUE THREAD

**Issue by nchen4** [BioPharmSoftGrp/BaSS#80]
Using BaSS::CreateAppStandalone("StandAlone12") to generate a standalone app, it runs well. However, when I use the AddTab function, I got some errors: 
 BaSS::AddTab("Simulation")
Error in file.copy(from = vCurrentPaths, to = strDestDirectory) :
  more 'from' files than 'to' files
Called from: file.copy(from = vCurrentPaths, to = strDestDirectory)
Browse[1]>

**Comment by jwildfire** [comment]
`AddTab()` assumes apps are packages by default. You can add a tab to a non-package app by setting `strType:"standalone"` like this:  `BaSS::AddTab("Simulation", strType="standalone")`
